FROM golang:1.23-alpine AS builder

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build -o grpc-server ./src/cmd/grpc/main.go

FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /app/grpc-server .

COPY .env .

RUN adduser -D appuser
RUN chown -R appuser:appuser /app
USER appuser

CMD ["./grpc-server"] 